### ISSUE TITLE
Conflict with Bob's Character classes

### ISSUE THREAD

**Issue by tractortractor** [ElmarWueest/Recexplo#15]
Character classes mod adds new playable classes. Those new classes are displayed in "made in:" section when some recipes are selected. When trying to record one of those recipes game crashes with error:

```
 374.344 Error MainLoop.cpp:1035: Exception at tick 18321: Error while running event RecExplo::on_gui_click (ID 1)
__RecExplo__/lua/recipe_cal.lua:391: attempt to perform arithmetic on field 'crafting_speed' (a nil value)
```

Looks like mod treats those new characters as factories and tries to use their non-existent crafting_speed value.

My small workaround which fixed this bug:
in file lua/recipe_cal.lua on lines 90 and 293
replaced
`	if entity.name == "player" then`
with
`	if entity.name == "player" or entity.crafting_speed == nil then`

How to reproduce the bug:
1. Disable all mods.
2. Install/enable following mods: "Bob’s Functions Library mod", "Bob’s multiple characters and classes" and "Recipe Explorer".
3. Start new game.
4. Record the very first "Wooden chest" recipe.

**Comment by ElmarWueest** [comment]
will be fixed in the new version 0.16.11

Thank you for your small workaround suggestion he seems to work.
To find this workaround you had looked quite deeply in my code. feel free to comment my code quality or anything else related to de code.

Thank you for your bug reports.
Do you have any suggestions for some optimisation or additional feature. Let me know it.
